In [1]:
import pandas as pd

df=pd.read_csv("C:\\Users\\ADMIN\\Downloads\\customer_shopping_behavior.csv")

In [2]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [3]:
df.shape

(3900, 18)

In [4]:
df.sort_values(by="Age")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
2224,2225,18,Male,Gloves,Accessories,25,Nebraska,L,Charcoal,Winter,4.3,No,Standard,No,No,38,Cash,Quarterly
2241,2242,18,Male,Jacket,Outerwear,77,Maryland,M,Purple,Summer,3.5,No,Free Shipping,No,No,3,Bank Transfer,Bi-Weekly
1612,1613,18,Male,Skirt,Clothing,68,Wisconsin,M,Indigo,Summer,4.4,No,Standard,Yes,Yes,26,Venmo,Monthly
418,419,18,Male,Sweater,Clothing,73,Illinois,L,Purple,Spring,3.0,Yes,Standard,Yes,Yes,27,Venmo,Bi-Weekly
736,737,18,Male,Dress,Clothing,58,Colorado,L,Maroon,Spring,2.9,Yes,2-Day Shipping,Yes,Yes,32,Credit Card,Every 3 Months
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,330,70,Male,Socks,Clothing,31,Nevada,S,White,Summer,2.9,Yes,2-Day Shipping,Yes,Yes,34,Bank Transfer,Monthly
325,326,70,Male,Pants,Clothing,70,Vermont,M,Charcoal,Winter,4.3,Yes,Free Shipping,Yes,Yes,38,Debit Card,Annually
1605,1606,70,Male,Belt,Accessories,46,Connecticut,M,Lavender,Winter,3.4,No,Next Day Air,Yes,Yes,15,Credit Card,Bi-Weekly
1122,1123,70,Male,Handbag,Accessories,62,North Carolina,S,Charcoal,Spring,4.3,No,2-Day Shipping,Yes,Yes,12,Credit Card,Annually
921,922,70,Male,Coat,Outerwear,24,South Dakota,L,Silver,Summer,4.1,Yes,Express,Yes,Yes,18,PayPal,Weekly

In [5]:
df[['Customer ID','Age','Gender']].head(10)

   Customer ID  Age Gender
0            1   55   Male
1            2   19   Male
2            3   50   Male
3            4   21   Male
4            5   45   Male
5            6   46   Male
6            7   63   Male
7            8   27   Male
8            9   26   Male
9           10   57   Male

In [6]:
df.iloc[3:1:-1][['Customer ID','Age','Gender']]

   Customer ID  Age Gender
3            4   21   Male
2            3   50   Male

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns=df.columns.str.lower().str.replace(" ","_")

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
df.columns=df.columns.str.replace("purchase_amount_(usd)","purchase_amount")

In [14]:
df["age_group"]=pd.cut(df["age"],bins=[0,18,35,60,100],labels=["child","youth","adult","senior"])

In [15]:
frequency_of_mapping={'Fortnightly':14, 'Weekly':7, 'Annually':365, 'Quarterly':91, 'Bi-Weekly':14,
       'Monthly':30, 'Every 3 Months':90}
df["purchase_of_frequency"]=df["frequency_of_purchases"].map(frequency_of_mapping)

In [16]:
(df["discount_applied"]==df["promo_code_used"]).all()

np.True_

In [17]:
df=df.drop(columns=["promo_code_used"])

In [21]:
!pip install pyodbc sqlalchemy
from sqlalchemy import create_engine
from urllib.parse import quote_plus

Requirement already satisfied: pyodbc in c:\users\admin\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\admin\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [44]:

host="localhost"


database="customer_behaviour"
driver=quote_plus("ODBC Driver 18 for SQL Server")
engine=create_engine(f"mssql+pyodbc://@{host}/{database}?driver={driver}"f"&trusted_connection=yes&TrustServerCertificate=yes")

In [45]:
table_name="customer_behaviour"
df.to_sql(table_name,engine,if_exists="replace",index=False)

c:\Users\ADMIN\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

50

Connected Successfully